### ISSUE TITLE
Spinner Freezes

### ISSUE THREAD

**Issue by jdonnell01** [daattali/shinycssloaders#20] opened 2018-06-26 21:55 UTC
Just before my Shiny app completes loading the css spinner freezes for a few seconds and then renders the output. This seems to happen when there is a function call to shinyapp.js which takes about three seconds, after which the page is loaded. During those three seconds the spinner is frozen. Is there a way to remediate this issue?

**Comment by KHBHH** [comment] 2018-08-23 15:37
Hi!

I have an app working on it in R. I use package called (shinycssloaders), and put my output inside in the (withspinner). I have the same issue as you where my output is loaded, and the spinner freezes for some amount of time, and I don't know why! Did you figure out what is the reason behind that behavior? If yes, I would highly appreciate your support!

Thank you!

**Comment by Cstaf** [comment] 2018-11-17 09:11
I'm also experiencing this issue.

**Comment by daattali** [comment] 2020-05-03 01:32
If this issue is still happening, could one of you please send a minimal reproducible example?

**Comment by daattali** [comment] 2020-07-23 01:29
Closing this issue as no information has been given and it's over 2 years old. If there are issues, feel free to open an issue.

**Closed by daattali** 2020-07-23 01:29 UTC
